[package]
name = "process_monitor"
version = "0.1.0"
authors = ["Petko Georgiev <petko.vas.georgiev@gmail.com>"]
edition = "2018"

[dependencies]
nix = "0.13.0"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_22"]
